### ISSUE TITLE
Create md5 hash from username

### ISSUE THREAD

**Issue by oubiwann** [lfex/try.lfe.io#16]
Upon clicking "submit" in the "login" modal, these things should happen:
- [ ] create a JS function which can `POST` to the REST server (can go in `trylfe.js`)
- [ ] username is posted to new "/login" URL
- [ ] function is called which extracts username from `arg-data` (see `trylfe-rest.lfe` for an example)
- [ ] implement this function in `trylfe-rest.lfe`
- [x] also extract referrer IP address/hostname from `arg-data` (this may require pulling in a YAWS record from one of YAWS' `.hrl` files)
- [x] calculate an md5 based upon these two data

**Comment by oubiwann** [comment]
@yurrriq This is another one you could jump into; the JS should be minimal, and there's some good LFE to enjoy :-)

**Comment by oubiwann** [comment]
Getting the IP address did require `include-lib`ing one of the YAWS `.hrl` files. Change set: b102adf24d1f62fd60a3c58e9727a81e4f75f39d

**Comment by yurrriq** [comment]
Cool. I like [superagent](https://github.com/visionmedia/superagent) for JS HTTP requests.

**Comment by oubiwann** [comment]
We've got jquery right now; that should be sufficient for our needs (don't want to make this too heavy in the browser ...)

**Comment by yurrriq** [comment]
:+1:

**Comment by oubiwann** [comment]
I think we're going to not take this approach ... instead, just create sessions by client IP address.
