### ISSUE TITLE
Style the console

### ISSUE THREAD

**Issue by oubiwann** [lfex/try.lfe.io#5]

**Comment by oubiwann** [comment]
I've got a teaser for you guys ... :-)

![screen shot 2015-08-19 at 6 52 32pm](https://cloud.githubusercontent.com/assets/894251/9372374/7c6166b8-46a3-11e5-8c37-af81924d576d.png)

**Comment by yurrriq** [comment]
:heart_eyes_cat:

**Comment by oubiwann** [comment]
Alight, this task is done.
