### ISSUE TITLE
Implement REST server

### ISSUE THREAD

**Issue by oubiwann** [lfex/try.lfe.io#7]

**Comment by yurrriq** [comment]
What does HTTP session management look like in LFE? With a hint, I could tackle this one.

**Comment by oubiwann** [comment]
I'm mostly done with this already ...

**Comment by yurrriq** [comment]
Awesome. Maybe my role is more test, learn and spread the word. Are there any tasks you think I, in particular, should work on? Maybe something you just don't feel like doing ha

**Comment by oubiwann** [comment]
I'm not sure if the shell processor is going to be needed, so #9 is not a good one to tackle. #10, #11, and #12 are all devops with Docker, so not too much LFE there ...  I think you and @rvirding have addressed #3 and that can probably get closed now. I've just closed #1. #2 is waiting on #7 and #8.

(this is all me thinking out loud, btw)

So the things that can be done now are:
- finish up the first version of the REST server (almost done there)
- write the LFE shell manager (which is involved), or
- hack on Docker stuff

everything else is waiting on one or more of these. If the Docker stuff isn't turning your crank, you could take a stab at the LFE shell manager ... but just know that the shell manager code is probably the bit that will change the most and the first couple iterations of that might get thrown out :-/

These are all the reasons I didn't delegate anything ... there's a lot that's up in the air.

**Comment by yurrriq** [comment]
Sounds good to me. I'm happy seeing all this progress, even if my hands stay clean. Thanks for all your explanations today. I think we're on the same page now. Erlang is so great...

**Comment by oubiwann** [comment]
Basic REST server is in place -- we can extend this as needed for future additions.
